name: azure-resources

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  TEST_ENV: "Test123"

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: test_job
      run: echo "test job"
## repo creation job
  repo_creation_job:
    needs: [test_job]
    runs-on: ubuntu-latest
    steps:
    - name: repo_checkout
      uses: actions/checkout@v3
    
    - name: repo_creation_script
      run: bash github_repo.sh kgopi1/azure-resources1
      working-directory: scripts
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

      ## Terraform Job:
## terraform job
  terraform_resources_job:
    needs: [repo_creation_job]
    runs-on: ubuntu-latest
    steps:

    - name: repo-checkout
      uses: actions/checkout@v3 

    - name: terraform-installation  
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: get-tf-version
      run: |
        terraform --version

    - name: terraform-init
      run: terraform init
      working-directory: infra
  
    - name: terraform-plan
      run: terraform plan
      working-directory: infra

    - name: terraform-apply
      run: terraform apply --auto-approve
      working-directory: infra
## Build job:
  build_appcode_job:
    needs: [repo_creation_job]
    runs-on: ubuntu-latest
    steps:
    - name: build_appcode
      run: echo "buildappcode"

## Release job:

  release_appcode_job:
    needs: [repo_creation_job, build_appcode_job]
    runs-on: ubuntu-latest
    steps:
    - name: release_appcode
      run: echo "release app code"

