name: azure-resources

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: test-bash-script
      run: ls -la 
      
  repo_creation_job:
    runs-on: ubuntu-latest
    steps:
    - name: repo_creation_script
      run: bash ${GITHUB_WORKSPACE}/scripts/github_repo.sh $repoName
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  terraform_resources_job:
    runs-on: ubuntu-latest
    steps:
    - name: terraform_init
      run: echo "Hello Terraform init"
  build_appcode_job:
    runs-on: ubuntu-latest
    steps:
    - name: build_appcode
      run: echo "buildappcode"
  release_appcode_job:
    runs-on: ubuntu-latest
    steps:
    - name: release_appcode
      run: echo "release app code"



