name: azure-resources

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all
  #repository-projects: write

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: test-bash-script
      run: ls -la 
      working-directory: scripts

  repo_creation_job:
    needs: [test_job]
    runs-on: ubuntu-latest
    steps:
    - name: repo_checkout
      uses: actions/checkout@v3
    
    - name: repo_creation_script
      run: bash github_repo.sh kgopi1/gopi1234
      working-directory: scripts
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 ## Terraform Job:

  terraform_resources_job:
    needs: [repo_creation_job]
    runs-on: ubuntu-latest
    steps:
    - name: terraform_init
      run: echo "Hello Terraform init"


## Build job:

  build_appcode_job:
    needs: [repo_creation_job]
    runs-on: ubuntu-latest
    steps:
    - name: build_appcode
      run: echo "buildappcode"

## Release job:

  release_appcode_job:
    needs: [repo_creation_job, build_appcode_job]
    runs-on: ubuntu-latest
    steps:
    - name: release_appcode
      run: echo "release app code"



